const ADD_TO_CART = 'ADD_TO_CART';

const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export default {
    ADD_TO_CART,
    REMOVE_FROM_CART,
    REMOVE_PRODUCT_FROM_CART
};