const REQUEST_PRODUCTS_JSON = 'REQUEST_PRODUCTS_JSON';
const RECEIVE_PRODUCTS_JSON = 'RECEIVE_PRODUCTS_JSON';
const FAILED_PRODUCTS_JSON = 'FAILED_PRODUCTS_JSON';

const REQUEST_SORT_PRODUCTS = 'REQUEST_SORT_PRODUCTS';
const REQUEST_FILTERED_PRODUCTS = 'REQUEST_FILTERED_PRODUCTS';
const REQUEST_SEARCHED_PRODUCTS = 'REQUEST_SEARCHED_PRODUCTS';

export default {
    REQUEST_PRODUCTS_JSON,
    RECEIVE_PRODUCTS_JSON,
    FAILED_PRODUCTS_JSON,
    REQUEST_SORT_PRODUCTS,
    REQUEST_FILTERED_PRODUCTS,
    REQUEST_SEARCHED_PRODUCTS
};